// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_9EHTsOv8OfDkr_wcZGjOXcObcbpTdI',
    appId: '1:731012682647:web:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '731012682647',
    projectId: 'school-management-system-79445',
    authDomain: 'school-management-system-79445.firebaseapp.com',
    storageBucket: 'school-management-system-79445.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_9EHTsOv8OfDkr_wcZGjOXcObcbpTdI',
    appId: '1:731012682647:android:b28149addd14821037aad2',
    messagingSenderId: '731012682647',
    projectId: 'school-management-system-79445',
    storageBucket: 'school-management-system-79445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_9EHTsOv8OfDkr_wcZGjOXcObcbpTdI',
    appId: '1:731012682647:ios:b28149addd14821037aad2',
    messagingSenderId: '731012682647',
    projectId: 'school-management-system-79445',
    storageBucket: 'school-management-system-79445.appspot.com',
    iosBundleId: 'com.funtech.sms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh_9EHTsOv8OfDkr_wcZGjOXcObcbpTdI',
    appId: '1:731012682647:ios:b28149addd14821037aad2',
    messagingSenderId: '731012682647',
    projectId: 'school-management-system-79445',
    storageBucket: 'school-management-system-79445.appspot.com',
    iosBundleId: 'com.funtech.sms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh_9EHTsOv8OfDkr_wcZGjOXcObcbpTdI',
    appId: '1:731012682647:web:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '731012682647',
    projectId: 'school-management-system-79445',
    authDomain: 'school-management-system-79445.firebaseapp.com',
    storageBucket: 'school-management-system-79445.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
